on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm install
      - run: npm run lint
      - run: npx vsce package
      - run: gh release create "${{ github.ref_name }}" *.vsix --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx vsce publish
        if: success()
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - run: npx ovsx publish *.vsix
        if: success()
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
